name: Push Docker Image
on:
  workflow_dispatch:
    inputs:
      image:
        description: 'docker image name'
        required: true
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout"
        uses: actions/checkout@v3

      - name: "Log into registry"
        run: |
          docker login --username ${{ secrets.DOCKER_REGISTRY_USERNAME }} \
            --password ${{ secrets.DOCKER_REGISTRY_PASSWORD }} \
            ${{ secrets.DOCKER_REGISTRY_HOST }}
      - name: "Push Image"
        run: |
          docker push ${{ github.event.inputs.publish_artifacts }} 
