name: Build docker image and push
on:
  workflow_call:
    inputs:
      image_name:
        required: true
        type: string
    secrets:
      DOCKER_REGISTRY_USERNAME: 
        required: true
      DOCKER_REGISTRY_PASSWORD: 
        required: true
      DOCKER_REGISTRY_HOST: 
        required: true
jobs:
  docker:
    runs-on: self-hosted
    steps:
      - name: Docker Login
        run: |
          docker login \
            -u ${{ secrets.DOCKER_REGISTRY_USERNAME }} \
            -p ${{ secrets.DOCKER_REGISTRY_PASSWORD }} \
            ${{ secrets.DOCKER_REGISTRY_HOST }}
      - name: Build and push Docker images
        run: |
          docker buildx build -t ${{ secrets.DOCKER_REGISTRY_HOST }}/${{ inputs.image_name }} .
